set -g default-terminal "screen-256color"
set -g status-interval 30
set -g status-right "#(whoami)@#(hostname -s) | AC: #(apm -a) | Batt: #(apm -l)%% | #(apm -m) minutes |  %a %Y-%m-%d  %I:%M%p"
set -g status-right-length 80
set -g mouse on
setw -g mouse on
